move archive extraction to separate function

diff --git a/ksp_installer b/ksp_installer
--- a/ksp_installer
+++ b/ksp_installer
@@ -12,8 +12,19 @@ GamePath="$(readlink -m "${1:-${pwd}}")"
 BASEURL="https://kerbalspaceprogram.com/"
 VERSION_REGEX="[0-9]-[0-9]{1,2}-[0-9]+"
 
-sighandler_EXIT()
-{
+extractArchiv() {
+			unzip "${1}" -d "$GamePath"
+			if [ $? != 0 ]; then
+				echo "Could not extract Archive"
+				exit 1
+			fi
+
+			#the archive contains the 'KSP_linux' directory, we move it's content to desired ${GamePath}
+			mv "${GamePath}/"KSP_linux/* "${GamePath}/"
+			rmdir "${GamePath}/"KSP_linux
+}
+
+sighandler_EXIT() {
 	rm -f cookies.txt "$(readlink -f "${0}")".tmp
 	if [ -f "ksp-linux-${latestVersion}.zip" ]; then
 	rm "ksp-linux-${latestVersion}.zip"
@@ -33,10 +44,7 @@ if [ ! -f "${GamePath}/KSP.x86_64" ]; then
 	then
 		archiveFile=$(find . -name "ksp-linux-*.zip" 2> /dev/null | sort | tail -n1 )
 		echo "But found $archiveFile"
-		unzip "$archiveFile" -d "${GamePath}"
-		#the archive contains the 'KSP_linux' directory, we move it's content to desired ${GamePath}
-		mv "${GamePath}/"KSP_linux/* "${GamePath}/"
-		rmdir "${GamePath}/"KSP_linux
+		extractArchiv "${archiveFile}"
 	else
 		echo "Download latest linux version from https://kerbalspaceprogram.com"
 
@@ -88,10 +96,7 @@ if [ ! -f "${GamePath}/KSP.x86_64" ]; then
 			trap 'sighandler_EXIT' 1 2 3 15
 			wget --load-cookies=cookies.txt "${BASEURL}lib/highwindsDwn.php?version=linux-${latestVersion}" -O "ksp-linux-$latestVersion.zip"
 			rm cookies.txt
-			unzip "ksp-linux-${latestVersion}.zip" -d "$GamePath"
-			#the archive contains the 'KSP_linux' directory, we move it's content to desired ${GamePath}
-			mv "${GamePath}/"KSP_linux/* "${GamePath}/"
-			rmdir "${GamePath}/"KSP_linux
+			extractArchiv "${archiveFile}"
 		fi
 	fi
 fi
